Add temporary workaround for better-sqlite3

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -67,8 +67,21 @@ jobs:
       run: PUBLIC_KEY="${{ secrets.SIGN_RELEASE_PUBLIC_KEY }}" SIGNAL_DIR="${{ github.workspace }}" node ./tmp-automation-release-scripts/patch-files.mjs
     - run: git diff
 
+    # Workaround for https://github.com/signalapp/Signal-Desktop/issues/7010
+    # Make sure to also switch back to "npm ci" instead of "npm install" later for better performance
+    - name: Temporary fix for better-sqlite3 (2024-09)
+      shell: bash
+      run: |
+        PACKAGE_JSON="package.json"
+        if grep -q '"@signalapp/better-sqlite3": "8.8.1"' "$PACKAGE_JSON"; then
+          # If the string exists, run sed to replace it
+          sed -i '' 's|"@signalapp/better-sqlite3": "8.8.1"|"@signalapp/better-sqlite3": "git://github.com/dennisameling/better-sqlite3.git#windows-arm64-workaround-2024-09"|' "$PACKAGE_JSON"
+        else
+          echo "Error: better-sqlite3 8.8.1 not found in $PACKAGE_JSON, it was probably updated by upstream Signal Desktop. This worarkound might no longer be needed!"
+          exit 1
+        fi
     - name: Install Desktop node_modules
-      run: npm ci --legacy-peer-deps
+      run: npm install --legacy-peer-deps
     - run: npm run generate
     - run: npm run build
       env:
